extends: handsome
parser: babel-eslint
globals:
  $: true
  _: true
  _rq: true
  _rqFeed: true
  _rqDecoder: true
  _rqDocCloneHTML: true
  _vds: true
  ace: true
  Highcharts: true
  html2canvas: true
  Pikaday: true
  Hogan: true
  MathJax: true
  JsDiff: true
  hljs: true
  QRious: true
  introJs: true
  WeixinJSBridge: true
  moment: true
  Swiper: true
  numeral: true
rules:
  flowtype/boolean-style:
    - error
    - boolean
  flowtype/define-flow-type: warn
  flowtype/delimiter-dangle:
    - error
    - never
  flowtype/generic-spacing:
    - error
    - never
  flowtype/no-primitive-constructor-types: error
  flowtype/object-type-delimiter:
    - error
    - comma
  flowtype/require-parameter-type: error
  flowtype/require-return-type:
    - error
    - always
    -
      annotateUndefined: never
  flowtype/require-valid-file-annotation: error
  flowtype/semi:
    - error
    - always
  flowtype/space-after-type-colon:
    - error
    - always
  flowtype/space-before-generic-bracket:
    - error
    - never
  flowtype/space-before-type-colon:
    - error
    - never
  flowtype/type-id-match:
    - error
    - ^([A-Z][a-z0-9]+)+Type$
  flowtype/union-intersection-spacing:
    - error
    - always
  flowtype/use-flow-type: warn
  flowtype/valid-syntax: warn
plugins:
  - flowtype
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
